### ISSUE TITLE
Overflow Error/ transfer amount exceeds allowance

### ISSUE THREAD

**Issue by bfreshhb** [bfreshhb/munch-contract#2]
To replicate the error:
before deploying, set the gas limit to double the default in remix.

1. Deploy RewardsPayouts
2. Make a muncher
3. Make a eatery
4. Rankup once or twice
5. call muncherPayOut

decoded output: "error": "Failed to decode output: Error: overflow (operation=\"setValue\", fault=\"overflow\", details=\"Number can only safely store up to 53 bits\", version=4.0.45)"``

**Comment by HunterBf** [comment]
When i debugged it, it seems like the issue was coming from the "safemath" library and that the IncreaseAllowance function didnt work, but I have no idea why....

**Comment by bfreshhb** [comment]
we are now burning/minting. transferring doesn't play a role.
